### PR TITLE
Audio merge

### PR DESCRIPTION
**Pull request by mkorcy**
@jcoyne @val99erie I don't want to excessively tag you guys so if this isn't helpful let me know, but this makes the necessary changes in MIRA to support the audio/audiotext merge, also retires some lingering refs to the wild life pathology model.

### CODE REVIEW

**Comment by mark-dce** [comment]
@mkorcy - this test isn't passing our CI server tests.  There appears to be an issue in our master branch as well. We'll get that fixed and then re-check whether this PR passed CI tests.

**Comment by val99erie** [comment]
@mkorcy  I don't mind if you tag me on PRs.  That way I'll notice it sooner.

The code looks good for this PR, but there are some broken specs.  Could you take a look at those?

**Comment by mkorcy** [comment]
@mark-dce hm, possibly because I forgot to bump tufts_models to post audio_merge after switching off my local copy, I've now bumped it.

**Comment by mkorcy** [comment]
yep that was it, sorry about that.

**Pull request merged**
