### PR TITLE
Update workflow_status display

### LINKED ISSUE #459: Change the "New" status indicator to "Unpublished" on draft objects
**ISSUE**
If I unpublish any published object, the status indicator goes back to "NEW" which isn't really true - it's not a new object.  We should use the term "UNPUBLISHED" instead.

Since we can't easily distinguish between truly "new" objects and previously published and now "unpublished" objects, I think it's best to use the term "unpublished" which covers both cases.

### PR DESCRIPTION
**Pull request by jcoyne**
Closes #459

* Changes "new" status to "unpublished" because existing items can enter this state after publication
* Moves display label to css for easier updates
* Shows label on all statuses (published, unpublished, edited) - change via css
* Shows "published" on any production (tufts:*) pids

### CODE REVIEW

**Comment by jcoyne** [comment]
This is the same as #465

**Comment by tonyc** [comment]
Mostly looks good, although the main thing here I disagree with is the CSS - since the markup is all the same, the HTML should go into a helper method called something like ```workflow_status(document)``` which then spits out the enclosing ```<span>``` 

Using ```&after: { content: 'foo' }``` in the CSS duplicates the business logic to ultimately put the same content in the markup, so the helper should output something like:

```html
  <span class="workflow-status <%= document.workflow_status %> col-md-12">
    <%= document.workflow_status %>&nbsp;
  </span>
```

The content can then later then be easily i18n'd when the need arises.

**Comment by jcoyne** [comment]
I agree with Tony, the page should have that content in the HTML.  (Consider accessibility issues)

**Comment by mark-dce** [comment]
I like the  i18n idea from the start - part of these changes were me objecting to the term "new" instead of "unpublished".  In part I was trying with the css thing to avoid burying the status labels in the code.

**Pull request merged**
